### ISSUE TITLE
issue with backtranslation method used

### ISSUE THREAD

**Issue by ghost** [iustinsirbu13/multimodal-ssl-for-disaster-tweet-classification#3]
Hi, in the paper it is mentioned that you use only russian as an intermediate language for backtranslation. But the code highlights the presence of two different augmentation strategies - en-de-en for text soft aug and en-de-fr-en for text hard aug. Since there is no de-fr model in the wmt models of fairseq, it is not clear to me how you made these augmentations. I was also not able to find your augmentation code for back-translation. Could you please help clarify?

these are the relevant files in your repo:
https://github.com/iustinsirbu13/multimodal-ssl-for-disaster-tweet-classification/blob/main/code/FixMatch-pytorch/train_fixmatch_mmbt_humanitarian_lu1_bt.cmd
https://github.com/iustinsirbu13/multimodal-ssl-for-disaster-tweet-classification/blob/main/code/scripts/merge_jsonl_files.py

**Comment by iustinsirbu13** [comment]
Hi,

Thanks for bringing this up!

The augmentation used is the one described in the paper (using Fairseq with Russian as an intermediate language). The references to some other augmentation strategies (e.g. en-de-fr-en) are just some artefacts from trying to use a different model for back-translation (I think it was MarianMT), but we ended up not using it in the final experiments. 

Regarding the code used for text augmentation, you can find at [https://github.com/iustinsirbu13/multimodal-ssl-for-disaster-tweet-classification?tab=readme-ov-file#code-references](https://github.com/iustinsirbu13/multimodal-ssl-for-disaster-tweet-classification?tab=readme-ov-file#code-references) the link to the Fairseq repository. We just used the models as described at [https://github.com/facebookresearch/fairseq/blob/main/examples/translation/README.md#example-usage-torchhub](https://github.com/facebookresearch/fairseq/blob/main/examples/translation/README.md#example-usage-torchhub), using the models `transformer.wmt19.en-ru` and `transformer.wmt19.ru-en`. 

Here is the used script. It seems like it was used separately in a Colab (probably because of some dependency issues on the local machine):

```python
!pip install fairseq
!pip install hydra-core==1.0.6
!pip install omegaconf
!!pip install fastBPE sacremoses subword_nmt

import pandas as pd
import numpy as np
import torch
import pickle
from tqdm import tqdm_notebook as tqdm
import os
import re
import pickle
import jsonlines
from tqdm import tqdm as tqdm

in_file = os.path.join(path, 'unlabeled.jsonl')
out_file = os.path.join(path, 'unlabeled_with_bt.jsonl')
num_aug = 4

en2ru = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.en-ru.single_model', tokenizer='moses', bpe='fastbpe')
ru2en = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.ru-en.single_model', tokenizer='moses', bpe='fastbpe')

ru2en.cuda()
en2ru.cuda()

def back_translate_ru(sentences):
    return ru2en.translate(en2ru.translate(sentences,  sampling = True, temperature = 0.9),  sampling = True, temperature = 0.9)

with jsonlines.open(in_file) as reader, jsonlines.open(out_file, 'w') as writer:
    for obj in tqdm(reader):
        sentence = obj['text']
        augs = back_translate_ru([sentence]*num_aug)
        obj['fairseq_ru'] = augs
        writer.write(obj)

```

Hope this helps!

**Comment by ghost** [comment]
Hi, thanks for clearing this up. What is the difference between strong augs and weak augs for text in this scenario? I can't imagine both being en-ru-en in this situation since the strong/hard augs need to be a more extreme set of transformations right?

**Comment by iustinsirbu13** [comment]
In the context of this paper, we used `--text_soft_aug "none"` and `--text_hard_aug "eda_01"` or `"fairseq_ru"`, which means that the weakly augmented text was the unaltered tweet, while the strongly augmented tweet was the tweet augmented using either EDA with 10% or back-translation. 
However, one could also experiment with different combinations for the 2 types of augmentations (e.g. EDA 10% as weak and BT as strong or maybe EDA 10% as weak and EDA 20% as strong, etc.)

**Comment by ghost** [comment]
Thank you for clearing this up. I will try reproducing the results with this.
